const products = [
  {
    category: 'electronic',
    name: 'iPhone 13',
    count: 10,
    price: 2000,
    id: 1,
  },
  {
    category: 'electronic',
    name: 'Samsung S20',
    count: 5,
    price: 1900,
    id: 2,
  },
  {
    category: 'electronic',
    name: 'meizu note',
    count: 6,
    price: 900,
    id: 3,
  },
  {
    category: 'electronic',
    name: 'Shotgun',
    count: 100,
    price: 500,
    id: 4,
  },
  {
    category: 'electronic',
    name: 'Samsung Buds',
    count: 10,
    price: 300,
    id: 5,
  },
  {
    category: 'tools',
    name: 'Generator',
    count: 12,
    price: 3500,
    id: 6,
  },
  {
    category: 'tools',
    name: 'Generator3GZ',
    count: 2,
    price: 7500,
    id: 7,
  },
  {
    category: 'tools',
    name: 'drill',
    count: 30,
    price: 230,
    id: 8,
  },
  {
    category: 'tools',
    name: 'drill wirless',
    count: 23,
    price: 330,
    id: 9,
  },
  {
    category: 'tools',
    name: 'multimeter',
    count: 5,
    price: 660,
    id: 10,
  },
  {
    category: 'tools',
    name: 'electric plane',
    count: 10,
    price: 190,
    id: 11,
  },
  {
    category: 'plumbing',
    name: 'wash basin',
    count: 20,
    price: 450,
    id: 12,
  },
  {
    category: 'plumbing',
    name: 'washbasin faucet',
    count: 50,
    price: 100,
    id: 13,
  },
  {
    category: 'plumbing',
    name: 'toilet bowl',
    count: 40,
    price: 500,
    id: 14,
  },
  {
    category: 'plumbing',
    name: 'bathtub',
    count: 3,
    price: 5000,
    id: 15,
  },
];
